name: flashbros
services:
  demo-website:
    image: demo-website
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hardhat:
    image: hardhat
    ports:
      - 8545:8545

